[package]
name = "desert-terminator"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[dependencies]
bevy = "0.8"
bevy_ecs_tilemap = "0.7.0"
iyes_loopless="0.7.1"
rand="0.8.5"